version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app          
      - /app/node_modules  
    environment:
      - PORT=5000
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env
