name: Build, Push and Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/graphic-backend:latest

    - name: Deploy to Remote Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/graphic-backend:latest
          docker stop graphic-backend || true
          docker rm graphic-backend || true
          docker run -d \
            --name graphic-backend \
            -p 5000:5000 \
            --env-file /home/${{ secrets.REMOTE_USER }}/backend.env \
            ${{ secrets.DOCKER_USERNAME }}/graphic-backend:latest
